membersrvc:
  image: hyperledger/fabric-membersrvc
  ports:
    - "7054:7054"
  command: membersrvc
vp1:
  image: hyperledger/fabric-peer
  ports:
    - "7050:7050"
    - "7051:7051"
    - "7053:7053"
  environment:
    - CORE_PEER_ID=vp1
    - CORE_PEER_ADDRESSAUTODETECT=true
    - CORE_VM_ENDPOINT==unix:///var/run/docker.sock
    - CORE_LOGGING_LEVEL=DEBUG
    - CORE_PEER_PKI_ECA_PADDR=membersrvc:7054
    - CORE_PEER_PKI_TCA_PADDR=membersrvc:7054
    - CORE_PEER_PKI_TLSCA_PADDR=membersrvc:7054
    - CORE_PEER_DISCOVERY_ROOTNODE=54.203.5.102:7051
    #- CORE_PEER_VALIDATOR_CONSENSUS_PLUGIN=pbft
  links:
    - membersrvc
  command: sh -c "sleep 5; peer node start --peer-chaincodedev"
