vp1:
  image: hyperledger/fabric-peer
  ports:
    - "7050:7050"
    - "7051:7051"
    - "7053:7053"
  environment:
    - CORE_PEER_ID=vp1
    - CORE_PEER_ADDRESSAUTODETECT=true
    - CORE_VM_ENDPOINT==unix:///var/run/docker.sock
    - CORE_LOGGING_LEVEL=DEBUG
    - CORE_PEER_PKI_ECA_PADDR=0.0.0.0:7054
    - CORE_PEER_PKI_TCA_PADDR=0.0.0.0:7054
    - CORE_PEER_PKI_TLSCA_PADDR=0.0.0.0:7054
    #- CORE_PEER_DISCOVERY_ROOTNODE=54.187.88.181:7051
    #- CORE_PEER_VALIDATOR_CONSENSUS_PLUGIN=pbft
  command: sh -c "peer node start --peer-chaincodedev"
